FROM php:7.2-apache

RUN sh -c 'apt-get update \
    && apt-get install -y libjpeg62-turbo-dev libfreetype6-dev libpng-dev \
    && apt-get install -y zlib1g-dev \
    && docker-php-ext-install zip \
    && a2enmod rewrite \
    && docker-php-ext-install mysqli \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd'

RUN curl -fsSL 'https://xdebug.org/files/xdebug-2.7.2.tgz' -o xdebug.tar.gz \
    && mkdir -p xdebug \
    && tar -xf xdebug.tar.gz -C xdebug --strip-components=1 \
    && rm xdebug.tar.gz \
    && ( \
    cd xdebug \
    && phpize \
    && ./configure --enable-xdebug \
    && make -j$(nproc) \
    && make install \
    ) \
    && rm -r xdebug \
    && docker-php-ext-enable xdebug

ENV IS4WFW_DEVELOPMENT=true

COPY ./docker/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini