<?php
	//+ěščřžýáíéúů

	require_once('scripts/php/includes/settings.inc.php');
	require_once("scripts/php/includes/database.inc.php");
	require_once("scripts/php/libs/Database.class.php");

	$db = new Database();
	$db->execute('update `directory` set `name` = "Naše krásná školička", `timestamp` = 1336984340 where `name` = "Nase krasna skolicka" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Ve třídě", `timestamp` = 1336984341 where `name` = "Ve tride" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "V nové PC učebně", `timestamp` = 1336984342 where `name` = "V nove PC ucebne" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Keramická dílna", `timestamp` = 1336984343 where `name` = "Keramicka dilna" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Starší PC učebna", `timestamp` = 1336984344 where `name` = "Starsi PC ucebna" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Ředitelna", `timestamp` = 1336984345 where `name` = "Reditelna" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "PC pro 1stupeň", `timestamp` = 1336984346 where `name` = "PC pro 1stupen" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Družina", `timestamp` = 1336984347 where `name` = "Druzina" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Školní jídelna", `timestamp` = 1336984348 where `name` = "Skolni jidelna" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Besedy s PČR", `timestamp` = 1336984349 where `name` = "Besedy s PCR" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Florbal-krajské finále", `timestamp` = 1336984350 where `name` = "Florbal-krajske finale" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Zápis 2007", `timestamp` = 1336984351 where `name` = "Zapis 2007" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Radovánky na sněhu", `timestamp` = 1336984352 where `name` = "Radovanky na snehu" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "2.B v ZOO", `timestamp` = 1336984353 where `name` = "2.B v ZOO" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Basketbalový potěr", `timestamp` = 1336984354 where `name` = "Basketbalovy poter" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Rozdávání vysvědčení 2.B", `timestamp` = 1336984355 where `name` = "Rozdavani vysvedceni 2.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Hodina ve 2.B", `timestamp` = 1336984356 where `name` = "Hodina ve 2.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Školní besídka v 1.B", `timestamp` = 1336984357 where `name` = "Skolni besidka v 1.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Plavání 3.B, 5.A", `timestamp` = 1336984358 where `name` = "Plavani 3.B, 5.A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Halloween 3.B", `timestamp` = 1336984359 where `name` = "Halloween 3.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Tři králové", `timestamp` = 1336984360 where `name` = "Tri kralove" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Mikuláš 2007", `timestamp` = 1336984361 where `name` = "Mikulas 2007" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Návštěva v útulku", `timestamp` = 1336984362 where `name` = "Navsteva v utulku" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Škola v přírodě", `timestamp` = 1336984363 where `name` = "Skola v prirode" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Maškarní", `timestamp` = 1336984364 where `name` = "Maskarni" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Den naruby", `timestamp` = 1336984365 where `name` = "Den naruby" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Šerpování 1.A", `timestamp` = 1336984366 where `name` = "Serpovani 1.A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Šerpování 1.B", `timestamp` = 1336984367 where `name` = "Serpovani 1.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Volby 4.B", `timestamp` = 1336984368 where `name` = "Volby 4.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Nové hřiště", `timestamp` = 1336984369 where `name` = "Nove hriste" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Čerti 4.B", `timestamp` = 1336984370 where `name` = "Certi 4.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Okresní finále - florbal", `timestamp` = 1336984371 where `name` = "Okresni finale - florbal" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Čarodějnice", `timestamp` = 1336984372 where `name` = "Carodejnice" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Tříkrálová sbírka", `timestamp` = 1336984373 where `name` = "Trikralova sbirka" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "1.B-2010", `timestamp` = 1336984374 where `name` = "1.B-2010" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "První dny ve škole", `timestamp` = 1336984375 where `name` = "Prvni dny ve skole" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Země snů", `timestamp` = 1336984376 where `name` = "Zeme snu" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Indiánský den", `timestamp` = 1336984377 where `name` = "Indiansky den" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Koncert", `timestamp` = 1336984378 where `name` = "Koncert" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Klaun v hodině čtení", `timestamp` = 1336984379 where `name` = "Klaun v hodine cteni" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Mikuláš", `timestamp` = 1336984380 where `name` = "Mikulas" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Vánoce 1.B", `timestamp` = 1336984381 where `name` = "Vanoce 1.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Vysvědčení", `timestamp` = 1336984382 where `name` = "Vysvedceni" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Práce s PC ", `timestamp` = 1336984383 where `name` = "Prace s PC " and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "1.B 2011 tělocvik", `timestamp` = 1336984384 where `name` = "1.B 2011 telocvik" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "1.B 2011 výuka", `timestamp` = 1336984385 where `name` = "1.B 2011 vyuka" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "ZOO", `timestamp` = 1336984386 where `name` = "ZOO" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Čarodějnice 2011", `timestamp` = 1336984387 where `name` = "Carodejnice 2011" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Malované počítaní 1.B", `timestamp` = 1336984388 where `name` = "Malovane pocitani 1.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Hřensko ", `timestamp` = 1336984389 where `name` = "Hrensko " and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "SuperStar", `timestamp` = 1336984390 where `name` = "SuperStar" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Kytlice", `timestamp` = 1336984391 where `name` = "Kytlice" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Pasování na čtenáře", `timestamp` = 1336984392 where `name` = "Pasovani na ctenare" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Dětský den", `timestamp` = 1336984393 where `name` = "Detsky den" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "První den ve 2. B", `timestamp` = 1336984394 where `name` = "Prvni den ve 2. B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Školní olympiáda - září 2011", `timestamp` = 1336984395 where `name` = "Skolni olympiada - zari 2011" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "3.A při hodině Aj", `timestamp` = 1336984396 where `name` = "3.A pri hodine Aj" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Olympiáda - vyhlašování vítězů", `timestamp` = 1336984397 where `name` = "Olympiada - vyhlasovani vitezu" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Maraton čtení", `timestamp` = 1336984398 where `name` = "Maraton cteni" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "2.B v parku", `timestamp` = 1336984399 where `name` = "2.B v parku" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Podzimní strašidýlka", `timestamp` = 1336984400 where `name` = "Podzimni strasidylka" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Plavání třetích tříd", `timestamp` = 1336984401 where `name` = "Plavani tretich trid" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Plavání druhých tříd", `timestamp` = 1336984402 where `name` = "Plavani druhych trid" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Výtvarná výchova ve 2.B", `timestamp` = 1336984403 where `name` = "Vytvarna vychova ve 2.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "2.B - při hodině matematiky", `timestamp` = 1336984404 where `name` = "2.B - pri hodine matematiky" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Exkurze 2.B", `timestamp` = 1336984405 where `name` = "Exkurze 2.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Vánoční tvoření", `timestamp` = 1336984406 where `name` = "Vanocni tvoreni" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Čertovské dovádění", `timestamp` = 1336984407 where `name` = "Certovske dovadeni" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Vánoce ve 2.B", `timestamp` = 1336984408 where `name` = "Vanoce ve 2.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "s 2.b při hodině Ma", `timestamp` = 1336984409 where `name` = "s 2.b pri hodine Ma" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "K+M+B 2012", `timestamp` = 1336984410 where `name` = "K+M+B 2012" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Ve školní tělocvičně s 2.b", `timestamp` = 1336984411 where `name` = "Ve skolni telocvicne s 2.b" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "děti z libochovické školky", `timestamp` = 1336984412 where `name` = "deti z libochovicke skolky" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "zápis 2012", `timestamp` = 1336984413 where `name` = "zapis 2012" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "vysvědčení jinak", `timestamp` = 1336984414 where `name` = "vysvedceni jinak" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "tvoření ve 2.b", `timestamp` = 1336984415 where `name` = "tvoreni ve 2.b" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Aquapark Kladno", `timestamp` = 1336984416 where `name` = "Aquapark Kladno" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Recitační soutěž", `timestamp` = 1336984417 where `name` = "Recitacni soutez" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Vaříme ve 3.A", `timestamp` = 1336984418 where `name` = "Varime ve 3.A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Vítání jara", `timestamp` = 1336984419 where `name` = "Vitani jara" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Výlet 5.A a 5.B", `timestamp` = 1336984420 where `name` = "Vylet 5.A a 5.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Tvoříme kraslice ve 2.B", `timestamp` = 1336984421 where `name` = "Tvorime kraslice ve 2.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Tělesná výchova ve 3. A", `timestamp` = 1336984422 where `name` = "Telesna vychova ve 3. A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Inspirace Emmou Srncovou - 3.A", `timestamp` = 1336984423 where `name` = "Inspirace Emmou Srncovou - 3.A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "PUTOVÁNÍ ZA PRAOTCEM ČECHEM", `timestamp` = 1336984424 where `name` = "PUTOVANI ZA PRAOTCEM CECHEM" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Exkurze v ČT", `timestamp` = 1336984425 where `name` = "Exkurze v CT" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Exkurze v ČT 1.A", `timestamp` = 1336984426 where `name` = "Exkurze v CT 1.A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Tvoření Den Země 1.A, 2.B, a 4.A", `timestamp` = 1336984427 where `name` = "Tvoreni Den Zeme 1.A, 2.B, a 4.A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Den Země 3.A a 9.A", `timestamp` = 1336984428 where `name` = "Den Zeme 3.A a 9.A" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "IX.B na Dni Země", `timestamp` = 1336984429 where `name` = "IX.B na Dni Zeme" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Den Země 6.B", `timestamp` = 1336984430 where `name` = "Den Zeme 6.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Den Země v 1.B", `timestamp` = 1336984431 where `name` = "Den Zeme v 1.B" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Indiánská školička", `timestamp` = 1336984432 where `name` = "Indianska skolicka" and `parent_id` = 25;');
	$db->execute('update `directory` set `name` = "Den čarodějnic", `timestamp` = 1336984433 where `name` = "Den carodejnic" and `parent_id` = 25;');

?>