FROM php:7.4-apache

RUN sh -c 'apt-get update \
    && apt-get install -y libjpeg62-turbo-dev libfreetype6-dev libpng-dev \
    && apt-get install -y libzip-dev zip \
    && docker-php-ext-install zip \
    && a2enmod rewrite \
    && docker-php-ext-install mysqli \
    && docker-php-ext-configure gd \
    && docker-php-ext-install gd'

EXPOSE 80

ENV IS4WFW_IN_DOCKER=true
ENV IS4WFW_INSTANCE_SETTINGS_PATH=/var/www/html/instance.inc.php

COPY ./src/.htaccess /var/www/html/.htaccess
COPY ./src/app /var/www/html/app

RUN sh -c 'mkdir -p /var/www/html/instance \
    /var/www/html/instance/cache \
    /var/www/html/instance/cache/images \
    /var/www/html/instance/cache/pages \
    /var/www/html/instance/cache/systemproperty \
    /var/www/html/instance/cache/templates \
    /var/www/html/instance/logs \
    /var/www/html/instance/modules \
    /var/www/html/instance/user \
    /var/www/html/instance/user/bundles \
    /var/www/html/instance/user/filesystem \
    /var/www/html/instance/user/public \
    && chmod 777 -R /var/www/html/instance'

COPY ./docker/php.conf /usr/local/etc/php-fpm.d/zz-log.conf
COPY ./docker/php.ini /usr/local/etc/php/conf.d/php-my.ini

COPY ./docker/src/instance.inc.php /var/www/html/instance.inc.php
COPY ./docker/src/modules /var/www/html/instance/modules
