ARG baseversion

FROM neptuo/is4wfw:$baseversion

ENV IS4WFW_DEVELOPMENT=true

RUN curl -fsSL 'https://xdebug.org/files/xdebug-2.9.7.tgz' -o xdebug.tar.gz \
    && mkdir -p xdebug \
    && tar -xf xdebug.tar.gz -C xdebug --strip-components=1 \
    && rm xdebug.tar.gz \
    && ( \
    cd xdebug \
    && phpize \
    && ./configure --enable-xdebug \
    && make -j$(nproc) \
    && make install \
    ) \
    && rm -r xdebug \
    && docker-php-ext-enable xdebug
    
EXPOSE 9000

COPY ./docker/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
